# Generated by Django 2.2.16 on 2020-12-27 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('emailaddress', models.CharField(max_length=200, unique=True)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('emailaddress', models.CharField(max_length=200, unique=True)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eventname', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('venue', models.CharField(max_length=200)),
                ('DateAndTime', models.DateTimeField()),
                ('TotalAvailableSeats', models.IntegerField()),
                ('Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Organizer')),
            ],
        ),
    ]
