# Generated by Django 2.2.16 on 2020-12-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='phonenumber',
            field=models.CharField(max_length=11),
        ),
    ]
