# Generated by Django 2.2.16 on 2020-12-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DateAndTime',
            field=models.CharField(max_length=100),
        ),
    ]
