# Generated by Django 2.2.16 on 2020-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201227_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DateAndTime',
            field=models.DateTimeField(),
        ),
    ]
